[package]
name = "zoom65v3"
version = "0.1.0"
description = "Reverse engineered hidapi bindings to zoom65v3 screen modules"
edition = "2021"

[dependencies]
thiserror = "2.0"
hidapi = "2.6"
chrono.workspace = true
